#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}

skip_commits:
  message: /updated readme.*/

#install:
#  - cinst pester

build: false

test_script:
# Test one-line deployment
  - ps: iex (New-Object Net.WebClient).DownloadString("https://gist.githubusercontent.com/CalebAlbers/582a06f352330479274892928a6b86ed/raw/c6f4c40a0ca2afc4f7db1e849157d4608c757463/install-it-glue-api-module") -Finalize
# pester tests coming soon
